"""Frozen initial schema. Future changes require new additive revisions."""
from alembic import op
import sqlalchemy as sa
revision="0001"
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisitions',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('acquired_at', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acquisitions_station'), 'acquisitions', ['station'], unique=False)
    op.create_index(op.f('ix_acquisitions_workspace'), 'acquisitions', ['workspace'], unique=False)
    op.create_table('alerts',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('measurement_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.Column('recovered_at', sa.String(), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_station'), 'alerts', ['station'], unique=False)
    op.create_index(op.f('ix_alerts_workspace'), 'alerts', ['workspace'], unique=False)
    op.create_table('assets',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('capacity_unit', sa.String(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('documentation', sa.JSON(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'station', 'code')
    )
    op.create_index(op.f('ix_assets_station'), 'assets', ['station'], unique=False)
    op.create_index(op.f('ix_assets_workspace'), 'assets', ['workspace'], unique=False)
    op.create_table('attachments',
    sa.Column('work_order_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('uploader', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_station'), 'attachments', ['station'], unique=False)
    op.create_index(op.f('ix_attachments_workspace'), 'attachments', ['workspace'], unique=False)
    op.create_table('audit',
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_station'), 'audit', ['station'], unique=False)
    op.create_index(op.f('ix_audit_workspace'), 'audit', ['workspace'], unique=False)
    op.create_table('edges',
    sa.Column('upstream', sa.String(), nullable=False),
    sa.Column('downstream', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('backup', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_station'), 'edges', ['station'], unique=False)
    op.create_index(op.f('ix_edges_workspace'), 'edges', ['workspace'], unique=False)
    op.create_table('import_batches',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_station'), 'import_batches', ['station'], unique=False)
    op.create_index(op.f('ix_import_batches_workspace'), 'import_batches', ['workspace'], unique=False)
    op.create_table('inventory',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('asset_code', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.CheckConstraint('quantity >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'station', 'name')
    )
    op.create_index(op.f('ix_inventory_station'), 'inventory', ['station'], unique=False)
    op.create_index(op.f('ix_inventory_workspace'), 'inventory', ['workspace'], unique=False)
    op.create_table('ledger',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'idempotency_key')
    )
    op.create_index(op.f('ix_ledger_station'), 'ledger', ['station'], unique=False)
    op.create_index(op.f('ix_ledger_workspace'), 'ledger', ['workspace'], unique=False)
    op.create_table('measurements',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('observed_at', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('processing', sa.String(), nullable=False),
    sa.Column('verification', sa.String(), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'station', 'asset_id', 'metric', 'observed_at')
    )
    op.create_index(op.f('ix_measurements_station'), 'measurements', ['station'], unique=False)
    op.create_index(op.f('ix_measurements_workspace'), 'measurements', ['workspace'], unique=False)
    op.create_table('replenishments',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'idempotency_key')
    )
    op.create_index(op.f('ix_replenishments_station'), 'replenishments', ['station'], unique=False)
    op.create_index(op.f('ix_replenishments_workspace'), 'replenishments', ['workspace'], unique=False)
    op.create_table('rules',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('recovery_threshold', sa.Float(), nullable=False),
    sa.Column('debounce', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_observed', sa.String(), nullable=True),
    sa.Column('active_alert', sa.String(), nullable=True),
    sa.Column('assumption', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_station'), 'rules', ['station'], unique=False)
    op.create_index(op.f('ix_rules_workspace'), 'rules', ['workspace'], unique=False)
    op.create_table('shipments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('eta', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('risk', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_station'), 'shipments', ['station'], unique=False)
    op.create_index(op.f('ix_shipments_workspace'), 'shipments', ['workspace'], unique=False)
    op.create_table('sources',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('verification', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('acquired_at', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('transformations', sa.JSON(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('licence', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_station'), 'sources', ['station'], unique=False)
    op.create_index(op.f('ix_sources_workspace'), 'sources', ['workspace'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('work_orders',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(length=80), nullable=False),
    sa.Column('station', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index(op.f('ix_work_orders_station'), 'work_orders', ['station'], unique=False)
    op.create_index(op.f('ix_work_orders_workspace'), 'work_orders', ['workspace'], unique=False)
    op.create_table('workspaces',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade():
    raise RuntimeError("Use a tested backup; destructive downgrade is prohibited")
